import type { Metadata, Viewport } from 'next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import './globals.css';

// ─── Metadata ────────────────────────────────────────────────────────────────

// Single source of truth for the canonical origin. Used as metadataBase so
// relative OG/icon URLs resolve against the real domain in production instead
// of defaulting to http://localhost:3000 (Next's fallback, which breaks social
// cards). NEXT_PUBLIC_SITE_URL is the name used across robots/sitemap/Stripe.
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://cuetrack.app';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'Cue Track — Click & Cue Tracks for Live Musicians',
    template: '%s | Cue Track',
  },
  description:
    'Generate professional click tracks and cue tracks for live musicians. Set your BPM, arrange song sections, add spoken cues, and download studio-quality WAV or MP3 in seconds.',
  keywords: [
    'click track',
    'cue track',
    'live music',
    'metronome track',
    'backing track',
    'BPM',
    'in-ear monitor',
    'IEM',
    'stage track',
    'song sections',
  ],
  authors: [{ name: 'Cue Track' }],
  creator: 'Cue Track',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: SITE_URL,
    siteName: 'Cue Track',
    title: 'Cue Track — Click & Cue Tracks for Live Musicians',
    description:
      'Generate professional click tracks and cue tracks for live musicians. Set your BPM, arrange song sections, add spoken cues, and download studio-quality audio in seconds.',
    // OG/Twitter images are served by the dynamic opengraph-image.tsx and
    // twitter-image.tsx routes in this directory — no static /og-image.png
    // file is required (and none exists).
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Cue Track — Click & Cue Tracks for Live Musicians',
    description: 'Generate professional click tracks and cue tracks for live musicians.',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // Favicon and apple-touch-icon are generated by app/icon.tsx and
  // app/apple-icon.tsx; the web manifest is served by app/manifest.ts. Next
  // wires these automatically, so no static /public icon files are needed.
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#f5f5f7',
  colorScheme: 'light',
};

// ─── Root Layout ─────────────────────────────────────────────────────────────

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
